spring:
  application:
    name: seochoPivot
  datasource:
    url: jdbc:mariadb://localhost:3306/test_collect
    username: collector
    password: 6382
    driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
#  file config(filepath: ???? / filename: ??? / fileExtension: ?? ??? / fileheader: ?? ?? ??)